import Head from 'next/head';
import { useEffect, useState } from 'react';
import Modal from '../../components/Modal';

function sendEmail () {
}

export default function Success () {
    return (
        <>
        <div style={{
            width: '100vw',
            height: '100vh',
            background: 'var(--purple)'
        }}>
            <Head>
            <title>HackBackBetter 2023</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            </Head>
            <Modal visible={true} setVisible={() => ''} hideCloseButton={true}>
            <div style={{
                width: '100%',
                height: '100%',
                border: 'none',
                borderRadius: '8px',
                border: '2px solid var(--purple)',
                display: 'flex',
                alignItems: 'center',
                flexDirection: 'column',
                justifyContent: 'center',
                padding: '40px',
                textAlign: 'center',
                position: 'relative'
            }}>
                <img src="https://cdn.hackbackbetter.live/logo-full-light.png" style={{ maxWidth: '30%', position: 'absolute', bottom: '2rem', right: '2rem' }} />
                <h1 style={{ marginBottom: '0px' }}>You've successfully cancelled your registration.</h1>
                <p>That's all you need to do. If you don't want to receive any more update emails from us (if you subscribed on our home page), please visit <a href="/unsubscribe" style={{ color: 'var(--purple)', textDecoration: 'underline' }}>this page</a> and fill out the form.</p>
                <p><b>What made you leave?</b> We would like to hear any feedback that you have for us, so please send us an email at <a href="mailto:info@hackbackbetter.live" style={{ color: 'var(--purple)', textDecoration: 'underline' }}>info@hackbackbetter.live</a> if you have any!</p>
            </div>
            </Modal>
        </div>
        </>
    );

}